### ISSUE TITLE
Missing Enchants\Runeforges

### ISSUE THREAD

**Issue by jcl8746** [Repooc/ElvUI_WrathArmory#13] opened 2022-10-09 15:56 UTC
![image](https://user-images.githubusercontent.com/12767327/194766794-d216e6c7-f3c3-4112-a321-6c45522add16.png)

I would also assume all DK runeforges are missing since 3883 is Nerubian Carapace.

**Comment by Repooc** [comment] 2022-10-09 17:18
duplicate of #7 & #9

**Closed by Repooc** 2022-10-09 17:18 UTC

**Comment by jcl8746** [comment] 2022-10-09 19:36
Sorry about that - I was using the latest at the time (https://github.com/Repooc/ElvUI_WrathArmory/commit/33c599604af74d7ae306d5b094ae35bf9c040f33) when I noticed this issue.

I will pull latest and test again once I can log in.

Thanks!

**Comment by jcl8746** [comment] 2022-10-09 21:55
**Update:** The issue was still happening when I updated to the latest. I figured out it was because I had `LibGetEnchant-1.0` installed for WeakAura (https://wago.io/ModernCharacterFrameClassic). Removing the `LibGetEnchant-1.0` install from the Addons folder has fixed the issue.

Just incase others keep reporting issues with missing IDs, it may be worth noting that any separate install of `LibGetEnchant-1.0` will cause issues until they update their lib to include the missing IDs and the problem isn't from WrathArmory.

@Repooc

**Comment by Repooc** [comment] 2022-10-10 00:52
> **Update:** The issue was still happening when I updated to the latest. I figured out it was because I had `LibGetEnchant-1.0` installed for WeakAura (https://wago.io/ModernCharacterFrameClassic). Removing the `LibGetEnchant-1.0` install from the Addons folder has fixed the issue.
> 
> Just incase others keep reporting issues with missing IDs, it may be worth noting that any separate install of `LibGetEnchant-1.0` will cause issues until they update their lib to include the missing IDs and the problem isn't from WrathArmory.
> 
> @Repooc

I assumed it was either you were out of date or you had the lib installed from another addon or something else... which is why i made the commit 7ae9a7f278cdbc76e28059967c18eef9a0893bf2 which is making my own instance of the library... normally i would just increment the version number but if someone else has been doing the same thing, then we will run into this issue again but doing this will make sure wratharmory uses my instance of it
