### ISSUE TITLE
Engi enchants not working

### ISSUE THREAD

**Issue by helmersson** [Repooc/ElvUI_WrathArmory#15] opened 2022-10-10 08:28 UTC
Hand-Mounted Pyro Rockets (3603) not working and giving a error message in chat.
Nitro Boots (3606) not working and giving a error message in chat.

**Comment by Repooc** [comment] 2022-10-10 08:40
duplicate of multiple of the same tickets (check closed tickets first)... you prob have the library i use installed which doesnt have the same info as i do and u did not read the instructions on what to report anyways

**Closed by Repooc** 2022-10-10 08:40 UTC
